name:  build mlir

env:
  LLVM_VERSION: 13.0.0

on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: create folders
        run: mkdir -p llvm install
        shell: bash
      - name: download llvm 13
        uses: robinraju/release-downloader@v1.2
        with:
          repository: llvm/llvm-project
          tag: llvmorg-${{ env.LLVM_VERSION }}
          fileName: llvm-project-${{ env.LLVM_VERSION }}.src.tar.xz
      - name: extract
        run: tar xvf llvm-project-${{ env.LLVM_VERSION }}.src.tar.xz --strip-components 1 -C llvm
      - name: setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: configure
        working-directory: llvm
        run: cmake -S llvm -B build -G Ninja -DCMAKE_INSTALL_PREFIX=${{ env.GITHUB_WORKSPACE }}/install -DLLVM_ENABLE_PROJECTS="mlir;clang" -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release -DLLVM_INSTALL_UTILS=ON
      - name: build
        working-directory: llvm
        run: cmake --build build --target check-mlir
      - name: install
        working-directory: llvm
        run: cmake --build build --target install
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: install
